import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { UrbanReportJSON } from '@/types/urbanReport';

export function generateReportPDF(report: UrbanReportJSON): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Header Box
  doc.setFillColor(11, 18, 17); // Dark theme
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(6, 214, 160); // Accent
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('URBAN INTELLIGENCE REPORT', 14, 22);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Location: ${report.location_name}`, 14, 32);
  doc.text(
    `Generated: ${new Date(report.generated_at).toLocaleString()}`,
    pageWidth - 14,
    32,
    { align: 'right' },
  );

  let yPos = 55;

  // Executive Summary
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, yPos);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  const splitSummary = doc.splitTextToSize(
    report.executive_summary,
    pageWidth - 28,
  );
  doc.text(splitSummary, 14, yPos + 8);
  yPos += splitSummary.length * 5 + 15;

  // AutoTable
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Key Environmental Metrics', 14, yPos);

  autoTable(doc, {
    startY: yPos + 5,
    head: [['Metric', 'Value', 'Status', 'Assessment']],
    body: report.key_metrics.map((m) => [
      m.label,
      `${m.value}${m.unit}`,
      m.status,
      m.description || '',
    ]),
    theme: 'grid',
    headStyles: {
      fillColor: [6, 214, 160],
      textColor: [11, 18, 17],
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [245, 250, 248] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 40 },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 'auto' },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Recommendations
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Actionable Recommendations', 14, yPos);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  yPos += 8;

  report.recommendations.forEach((rec) => {
    doc.setFillColor(6, 214, 160);
    doc.circle(16, yPos - 1, 1.5, 'F');
    const splitRec = doc.splitTextToSize(rec, pageWidth - 35);
    doc.text(splitRec, 22, yPos);
    yPos += splitRec.length * 5 + 3;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    'Generated by CityPulse AI Data Engine',
    pageWidth / 2,
    doc.internal.pageSize.height - 10,
    { align: 'center' },
  );

  doc.save(
    `CityPulse-Report-${report.location_name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`,
  );
}
